apiVersion: alibabacloud.com/v1
kind: AlbConfig
metadata:
  name: main-alb
spec:
  config:
    name: main-alb
    addressType: Internet
    zoneMappings:
    - vSwitchId: vsw-bp1wfz0oz34c6im76d2wl
    - vSwitchId: vsw-bp1gz3s16kbsn2iuxm9df
  listeners:
    - port: 80
      protocol: HTTP
    - port: 443
      protocol: HTTPS
      # TLS
      securityPolicyId: tls_cipher_policy_1_2_strict_with_1_3
      certificates:
      - CertificateId: 19967909-cn-hangzhou
        IsDefault: true
      # mTLS
      caEnabled: true
      caCertificates:
      - CertificateId: 91a82d5ea7fc4f8e921231b16f40b837
